//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.UserComments = new HashSet<UserComments>();
            this.UserQuery = new HashSet<UserQuery>();
        }
    
        public string userID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public Nullable<System.DateTime> userExpDate { get; set; }
        public Nullable<System.DateTime> userPasswordExpDate { get; set; }
        public string userCustomerData { get; set; }
        public string userCart { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ShoppingCarts ShoppingCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserComments> UserComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQuery> UserQuery { get; set; }
    }
}
